version: 2
updates:
  # Enable version updates for Docker
  # Docker compose currently not supported: https://github.com/dependabot/dependabot-core/issues/390
  # Dependabot currently doesn't support multi dirs: https://github.com/dependabot/dependabot-core/issues/2178
  - package-ecosystem: "docker"
    directory: "/grafana"
    schedule:
      interval: "monthly"
  - package-ecosystem: "docker"
    directory: "/influxdb"
    schedule:
      interval: "monthly"
  - package-ecosystem: "docker"
    directory: "/mqtt"
    schedule:
      interval: "monthly"
  - package-ecosystem: "docker"
    directory: "/mqtt-influxdb-forwarder"
    schedule:
      interval: "monthly"

  # Enable version updates for pip
  - package-ecosystem: "pip"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/mqtt-influxdb-forwarder"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "monthly"
    # target-branch: dependency-updates
    # labels:
    #   - "pip dependencies"

  # Enable version updates for actions
  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "monthly"
    # target-branch: dependency-updates
    # labels:
    #   - "workflow dependencies"
